[ClassVersion("1.0.0"), FriendlyName("xDSCWebService")] 
class MSFT_xDSCWebService : OMI_BaseResource
{
  [Key] string EndpointName;
  [required, Description("Can take the value AllowUnencryptedTraffic for setting up a non SSL based endpoint or the value CertificateGeneratedInSameConfig when a certificate is requested with the xCertReq resource in the same config.")]
  string CertificateThumbPrint;
  [write, Description("Required when the value CertificateGeneratedInSameConfig is used for CertificateThumbPrint")] 
  string Subject;
  [write] uint32 Port;
  [write] string PhysicalPath;
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [write,ValueMap{"Started","Stopped"},Values{"Started", "Stopped"}] string State;
  [write] string DatabasePath;
  [write] string ModulePath;
  [write] string ConfigurationPath;
  [read] string DSCServerUrl;  
  [write] string RegistrationKeyPath;
  [write] boolean AcceptSelfSignedCertificates;
  [required, Description("This property will ensure that the Pull Server is created with the most secure practices")] boolean UseSecurityBestPractices;
  [write,ValueMap{"SecureTLSProtocols"},Values{"SecureTLSProtocols"}] string DisableSecurityBestPractices [];
};
